version: "3.8"

services:
  books-api:
    build:
      context: ./books-api
      dockerfile: Dockerfile
    env_file:
      - ./envs/books-api.env
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://127.0.0.1:4000/health',(r)=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 3

  auth-proxy:
    build:
      context: ./auth-proxy
      dockerfile: Dockerfile
    env_file:
      - ./envs/auth-proxy.env
    ports:
      - "4100:4100"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://127.0.0.1:4100/health',(r)=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 3

  library-service:
    build:
      context: ./library-service
      dockerfile: Dockerfile
    env_file:
      - ./envs/library-service.env
    ports:
      - "4200:4200"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://127.0.0.1:4200/health',(r)=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 3

# opcional: frontend container (se quiser servir via nginx)
# frontend:
#   build:
#     context: ../../frontend-root
#     dockerfile: Dockerfile.frontend
#   ports:
#     - "3000:80"
#   depends_on:
#     - books-api
#     - auth-proxy
